version: '3'
services:
    app:
        env_file: .env
        container_name: app
        image: registration-system-project-for-interview:latest
        build: .
        restart: always
        depends_on: [mysql]
        ports: 
            - 3000:3000
    
    mysql:
        env_file: .env
        container_name: mysql
        image: mysql:5.7
        restart: always
        ports:
            - 3306:3306
        volumes:
            - ./mysql:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}