version: '3'
services:
    app:
        image: node:12.14.0-alpine
        working_dir: /usr/src/app
        volumes:
            - .:/usr/src/app
        command: 
            - /bin/sh
            - -c
            - |
                npm i
                npm run dev